/*
 jQuery JavaScript Library v1.6.4
 http://jquery.com/

 Copyright 2011, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2011, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Amazon elects to use jQuery and Sizzle under the MIT license.

 Date: Mon Sep 12 18:54:48 2011 -0400
*/
(function(){P.register("jQuery",function(){return window.AmazonUIjQuery})})();
(function(){P.when("jQuery").register("a-base",function(e){return{version:"3.0",$:e}});"use strict";P.when("a-base").register("a-util",function(e){var l=e.$,k=function(){function c(a,b,p){if(null!==a)if(Array.prototype.forEach&&a.forEach===Array.prototype.forEach)a.forEach(b,p);else if(a.length===+a.length)for(var f=0,n=a.length;f<n&&!(f in a&&b.call(p,a[f],f,a)===d);f++);else for(f in a)if(a.hasOwnProperty(f)&&b.call(p,a[f],f,a)==={})break}var d={};return{each:c,map:function(a,b,p){var f=[];if(null===
a)return f;if(Array.prototype.map&&a.map===Array.prototype.map)return a.map(b,p);c(a,function(n,q,a){f[f.length]=b.call(p,n,q,a)});a.length===+a.length&&(f.length=a.length);return f},reduce:function(a,b,p,f){var n=2<arguments.length;null===a&&(a=[]);if(Array.prototype.reduce&&a.reduce===Array.prototype.reduce)return n?a.reduce(b,p):a.reduce(b);c(a,function(q,a,c){n?p=b.call(f,p,q,a,c):(p=q,n=!0)});n||P.error("Reduce of empty array with no initial value","A.util","reduce");return p},breaker:d}}();
e=function(){return{delay:function(c,d){var a=Array.prototype.slice.call(arguments,2);return setTimeout(function(){return c.apply(null,a)},d)},interval:function(c,d){return setInterval(c,d)}}}();var h=function(){var c=/^\s+/,d=/\s+$/;return{trim:function(a){return String.prototype.trim?String.prototype.trim.call(a):a.replace(c,"").replace(d,"")},contains:function(a,b){return-1!==(""+a).indexOf(b)}}}(),m=function(){function c(){for(var b=arguments[0],a=1,f=arguments.length;a<f;a++)k.each(arguments[a],
function(n,f){var a;l.isArray(n)?(a=l.isArray(b[f])||l.isPlainObject(b[f])?b[f]:[],b[f]=c(a,n)):l.isPlainObject(n)?(a=l.isPlainObject(b[f])?b[f]:{},b[f]=c(a,n)):b[f]=n});return b}function d(b,a){b=b||{};a=a||{};var f={},n;for(n in b)b.hasOwnProperty(n)&&(f[n]="object"===typeof b[n]&&b[n]?d(b[n],a[n]):b[n]!==a[n]);for(n in a)a.hasOwnProperty(n)&&!f[n]&&(f[n]="object"===typeof a[n]&&a[n]?d(a[n],b[n]):a[n]!==b[n]);return f}function a(b,p){var f;if(b===p)return!0;if(l.isArray(b)){if(!l.isArray(p)||b.length!==
p.length)return!1;for(f=b.length;f--;)if(!a(b[f],p[f]))return!1;return!0}if(l.isPlainObject(b)){if(!l.isPlainObject(p))return!1;for(f in b)if(!a(b[f],p[1]))return!1;return!0}return!1}return{extend:c,diff:d,equals:a,copy:function(b){return l.isArray(b)?b.slice(0):l.isPlainObject(b)?c({},b):b},indexOfArray:function(b,a,f){if(Array.prototype.indexOf&&b.indexOf===Array.prototype.indexOf)return b.indexOf(a,f);b&&b instanceof Array||P.error("Invalid arr passed to A.indexOfArray: "+b,"A.util","indexOfArray");
f=parseInt(f,10);f=isNaN(f)?0:f;if(!isFinite(f))return-1;for(var n=b.length;f<n;f++)if(b[f]===a)return f;return-1}}}(),g=function(){return{onScreen:function(c){var d=l(c);if(!d.is(":visible"))return!1;var a=l(window);c=a.scrollTop();var a=window.innerHeight?window.innerHeight:a.height(),b=c+a;c-=100;var b=b+100,p=d.offset().top,d=d.height(),f=p+d;return p>=c&&p<b||f>c&&f<=b||d>a&&p<=c&&f>=b}}}();return{now:function(){return Date.now()},extend:m.extend,copy:m.copy,diff:m.diff,equals:m.equals,indexOfArray:m.indexOfArray,
parseJSON:function(c){return l.parseJSON(c)},delay:e.delay,interval:e.interval,trim:h.trim,contains:h.contains,map:k.map,reduce:k.reduce,each:k.each,breaker:k.breaker,onScreen:g.onScreen}});"use strict";P.register("a-defer",function(){function e(g){var c=0,d=setTimeout(function(){e(g)},0);if(h||0===g.length)clearTimeout(d),k=!1;else{var a=Date.now();try{g.shift().call()}catch(b){P.error("Deferred execution failed: "+b.message,"A.defer","partialExecute",b)}m+=Date.now()-a;50<m&&(c=50,m=0);setTimeout(function(){clearTimeout(d);
e(g)},c)}}var l=[],k=!1,h=!1,m=0;return{defer:function(g){l.push(g);k||h||(k=!0,setTimeout(function(){e(l)},0))},pauseDeferred:function(){h=!0},executeDeferred:function(){h=!1;k=!0;setTimeout(function(){e(l)},0)}}});"use strict";P.when("a-base","a-util").register("a-events",function(e,l){function k(b){g[b]=!0;d.subscribe(b,function(){P.register(b,function(){var b=window.aPageStart||l.now();return{time:l.now()-b}})});d.publish(b)}function h(){g.beforeLoad&&g.load||(k("beforeLoad"),k("load"),setTimeout(function(){k("beforeAfterLoad");
k("afterLoad")},1500))}var m=e.$,g={},c=m(window),d=function(){function b(){for(var f=setTimeout(b,0),a=l.now(),c;void 0!==(c=q.shift());)try{if(!1===c.fn.apply(window,c.args)){clearTimeout(f);for(var d=c.id,p=void 0,g=[],e=0,h=q.length;e<h;e++)p=q[e].id,d!==p&&g.push(q[e]);q=g}if(50<=l.now()-a){clearTimeout(f);l.delay(b,15);return}}catch(k){P.error("Event execution failed for event "+c.topic+": "+k.message,"A.events","partialPublish",k)}clearTimeout(f);n=!1}var a={},f=0,n=!1,q=[];return{publish:function(c){var d=
a[c];if(d){for(var g=Array.prototype.slice.call(arguments,1),e=f++,h=0,k=d.length;h<k;h++)q.push({topic:c,id:e,fn:d[h],args:g});n||(n=!0,b())}},subscribe:function(b,f){a[b]||(a[b]=[]);if("function"===typeof f)return a[b].unshift(f),{event:b,callback:f}},unsubscribe:function(b,f){if(a[b])if(f)for(var n=a[b],q=0,c=n.length;q<c;q++)n[q]===f&&n.splice(q,1);else a[b]=[]}}}(),a=function(){var b=function(b,f){for(var n=b.split(" "),a,c=[];void 0!==(a=n.pop());)g[a]?l.delay(f,0):c.push(d.subscribe(a,f).event);
return{event:c.join(" "),callback:f}};l.each("ready load unload afterLoad scroll resize orientationchange".split(" "),function(a,f){b[a]=function(){b.apply(window,[a].concat([].slice.call(arguments,0)))}});return b}();m(document).ready(function(){k("beforeReady");k("ready");k("afterReady");"complete"===document.readyState&&h()});c.load(h);c.unload(function(){k("unload")});return{on:a,off:function(b,a){"object"===typeof b&&(b=b.event,a=b.callback);return d.unsubscribe(b,a)},trigger:function(){d.publish.apply(window,
arguments)},events:{defaults:{input:"change",select:"change",a:"click",button:"click",form:"submit"}}}});"use strict";P.when("a-base","a-util","a-events").register("a-declarative",function(e,l,k){function h(c){var d=m(c.currentTarget),a=m(c.target),b=d.data("action");b&&(b=b.split(" "),l.each(b,function(b){var f=g[b]||{},n=d.data(b),q=c.type,n={$target:a,$currentTarget:d,targetTag:a.prop("tagName").toLowerCase(),type:q,action:b,data:n,$event:c,$declarativeParent:d},q="a:declarative:"+b;k.trigger(q,
n);k.trigger(q+":"+c.type,n);"a"!==d.prop("tagName").toLowerCase()||"click"!==c.type||"undefined"===typeof g[b]||f.allowLinkDefault||c.preventDefault()}))}var m=e.$,g={};m(document).delegate(".a-declarative","click mouseenter mouseleave mousemove change submit touchstart touchend touchmove touchcancel keydown keyup keypress",h).delegate(".a-gesture","tap swipe swipe-horizontal swipe-vertical pan-horizontal pan-vertical doubleTap",h);return{declarative:function(){var c,d,a,b;switch(arguments.length){case 2:c=
arguments[0];b=arguments[1];break;case 3:c=arguments[0];d=arguments[1];b=arguments[2];break;case 4:c=arguments[0],d=arguments[1],a=arguments[2],b=arguments[3]}c&&("string"===typeof c&&(c=l.trim(c).split(" ")),l.each(c,function(c){var f="a:declarative:"+c;g[c]=a||{};if(d)d="string"===typeof d?l.trim(d).split(" "):d,l.each(d,function(n){k.on(f+":"+n,b)});else k.on(f,b)}))}}});"use strict";P.when("a-base","a-util","a-events","a-declarative").register("a-state",function(e,l,k,h){function m(a,b){if(null===
b||c.isArray(b)||c.isPlainObject(b)){var p,f=d[a];p=l.copy(b);f=l.diff(f||p,p);d[a]=p;k.trigger("a:state:update:"+a,p,f,b);return p}P.error("Invalid value passed to A.state with a namespace of "+a+".  Value: "+b,"A.state","extendNamespace")}function g(a,b,c){if(1===b.length)return a[b.shift()]=c,a;a[b.shift()]=g({},b,c);return a}var c=e.$,d={};k.on("beforeReady",function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(!c.data(a[b],"a-eval")){var f=c(a[b]),n=f.attr("data-a-state");
n&&(n=l.parseJSON(n),n.key&&(f=l.parseJSON(f.html()),c.data(a[b],"a-eval",!0),m(n.key,f)))}});h.declarative("a-state",function(a){var b=a.$target,c=a.data.key,f=a.data[a.type];f||k.events.defaults[a.targetTag]!==a.type||(f=b.attr("name"));f&&c&&(b.is("select")&&(b=b.find(":selected")),void 0!==typeof b.val()&&"string"===typeof f&&(a=b.val(),b.is("input[type=checkbox]")&&!b.prop("checked")&&(a=null),f=g({},f.split("."),a)),m(c,f))});e=function(a,b){return void 0===b?l.copy(d[a]):m(a,b)};e.bind=function(a,
b){k.on("a:state:update:"+a,b)};return{state:e}});"use strict";P.when("a-base","a-util","a-events","a-declarative","a-state").register("a-ajax",function(e,l,k,h,m){function g(b){return b&&"string"!==typeof b?a.param(b):""}function c(b,f){b&&0!==b.length&&(b[0]instanceof Array||(b=[b]),l.each(b,function(a){var c=p[a[0]];c?c.apply(window,a):((c=f)||P.error("There is no handler for the streaming ajax command: "+b[0],"A.ajax","chunkHandler"),c(a))}))}function d(b,a){a=a||{};return f["a-ajax-update"]({url:b,
params:g(a.params),method:a.method,chunk:a.chunk,success:a.success,failure:a.failure||a.error,abort:a.abort,indicator:a.indicator,timeout:a.timeout})}var a=e.$,b=function(){window.XMLHttpRequest||(window.XMLHttpRequest=function(){return new ActiveXObject("Microsoft.XMLHTTP")});var b=function(){function b(){0<f.length?f.pop().send():a--}var f=[],a=0;return{add:function(b){4>a?(b.send(),a++):f.push(b)},complete:b,abort:function(a){l.each(f,function(b,n){if(b===a)return f.splice(n,1),l.breaker});b()}}}(),
f=function(){},a=function(f){var a=f.http,q=f.responsePosition,c=3===a.readyState,d=4===a.readyState&&(200===a.status||304===a.status);if(c||d)if(d=a.responseText,q<d.length){var q=d.substring(q,d.length),d=q.split("&&&"),p=q.lastIndexOf("&&&");if(-1===p&&c)return;p<q.length-3&&c&&d.pop();l.each(d,function(b,a){var n;try{n=l.parseJSON(b)}catch(q){l.delay(function(){P.error("Invalid streaming ajax JSON response: "+b,"A.ajax","streamingResponseHandler",q)},0)}f.callbacks.chunk(n)});f.responsePosition+=
p}4===a.readyState&&(a=200!==a.status&&304!==a.status?f.callbacks.failure:f.callbacks.success,clearInterval(f.pollTimer),clearTimeout(f.timeoutTimer),b.complete(),a.call(),k.trigger("a:pageUpdate"),k.trigger("a:ajax:complete"))},c=function(f){var a=f.http;if(4===a.readyState){var q=200!==a.status&&304!==a.status?f.callbacks.failure:f.callbacks.success;clearInterval(f.pollTimer);clearTimeout(f.timeoutTimer);b.complete();f=a.responseText;var c=l.trim(a.responseText),a=c.charAt(0),c=c.charAt(c.length-
1);if("["===a&&"]"===c||"{"===a&&"}"===c)f=l.parseJSON(f);q(f);k.trigger("a:ajax:complete")}};return function(){var d=function(){var b=new XMLHttpRequest;this.pollTimer=null;this.http=b;this.responsePosition=0;this.buffer="";this.callbacks={success:f,failure:f,chunk:f,abort:f}};d.prototype={send:function(){var f=this;this.http.send(this.params);this.pollTimer=setInterval(function(){if(2<=f.http.readyState&&"unknown"!==typeof f.http.responseText){var b=f.http.getResponseHeader("Content-Type");(b&&
-1!==b.toLowerCase().indexOf("application/amazonui-streaming-json")?a:c)(f)}},25);this.timeout="undefined"===typeof this.timeout?2E4:this.timeout;this.timeoutTimer=setTimeout(function(){4>f.http.readyState&&(clearInterval(f.pollTimer),f.callbacks.failure(),b.complete())},this.timeout)},get:function(f,a,q,c,d,p,s){var g=this.http,e=this;g.open("get",a?f+"?"+a:f);g.setRequestHeader("X-Requested-With","XMLHttpRequest");this.timeout=q;this.callbacks.chunk=c||this.callbacks.chunk;this.callbacks.success=
d||this.callbacks.success;this.callbacks.failure=p||this.callbacks.failure;this.callbacks.abort=s||this.callbacks.abort;b.add(this);return{abort:function(){e.abort()}}},abort:function(){this.http&&this.http.abort();clearInterval(this.pollTimer);clearTimeout(this.timeoutTimer);b.abort(this);this.callbacks.abort()},post:function(f,a,q,c,d,p,s){var g=this.http,e=this;g.open("post",f);g.setRequestHeader("Content-type","application/x-www-form-urlencoded");g.setRequestHeader("X-Requested-With","XMLHttpRequest");
this.params=a;this.timeout=q;this.callbacks.chunk=c||this.callbacks.chunk;this.callbacks.success=d||this.callbacks.success;this.callbacks.failure=p||this.callbacks.failure;this.callbacks.abort=s||this.callbacks.abort;b.add(this);return{abort:function(){e.abort()}}}};return d}()}(),p={update:function(b,f,c){a(f).html(c)},append:function(b,f,c){b=a(f);b.html(b.html()+c)},prepend:function(b,f,c){b=a(f);b.html(c+b.html())},state:function(b,f,a){m.state(f,a)},script:function(b,f){eval(f)}},f={"a-ajax-update":function(f){var q=
new b,d=f.abort,p=a(f.indicator);p.show();var g="string"===typeof f.method&&"post"===f.method.toLowerCase()?"post":"get";return q[g](f.url,f.params,f.timeout,function(b){c(b,f.chunk)},function(){p.hide();f.success&&f.success.apply(window,arguments)},function(){p.hide();f.failure&&f.failure.apply(window,arguments)},d)}};h.declarative("a-ajax-update",function(b){var a=b.$target,c=b.action,d=b.data;if(d||k.events.defaults[b.targetTag]===b.type)if("object"!==typeof d||d[b.type]){var d=d||{},p=d.url||
a.attr("href")||a.attr("action"),e=g(d.params),h=a.attr("method")||d.method,m=d.indicator,d=d.timeout;p||P.error("No ajax url provided.","A.ajax","declarativeHandler");"form"===b.targetTag&&b.type===k.events.defaults.form&&(a=a.serialize(),e+=a);b.$event.preventDefault();return f[c]({url:p,params:e,method:h,indicator:m,operation:c,timeout:d})}});return{ajax:d,get:function(b,f){f=f||{};f.method="get";return d(b,f)},post:function(b,f){f=f||{};f.method="post";return d(b,f)}}});"use strict";P.when("a-base",
"a-util","p-detect").register("a-animate",function(e,l,k){function h(b,a,c){var p={};p[a]=c;l.each(d,function(b){p[b+a]=c});b.css(p)}function m(b){var a="",d=k.capabilities.transform3d;b.top!==c&&b.left!==c?(a="("+b.top+"px, "+b.left+"px",d&&(a+=", 0"),a+=")"):(b.top!==c?a="translateY("+b.top+"px)":b.left!==c&&(a="translateX("+b.left+"px)"),d&&(a+=" translateZ(0)"));b.scale!==c&&(a+=" scale("+b.scale+")");return a}function g(b){var c={},d=!1;l.each(a,function(a){a in b&&(d=!0,c[a]=b[a],delete b[a])});
return d?c:null}var c,d=["-webkit-","-moz-","-khtml-","-o-","-ms-"],a=["top","left","scale"],b=function(){};e={animate:function(f,a,c,d,p){var g=f.data("a-animate")||{};g.props=g.props?l.extend(g.props,a):a;var e=b;g.callback&&(e=g.callback);g.callback=function(){f.data("a-animate",null);e();p&&p()};f.queue("fx",[function(){f.animate(g.props,{duration:c,easing:"linear"===d?d:"swing",complete:g.callback,queue:!1})}]);f.data("a-animate",g)},fadeIn:function(b,a,c,d){b.fadeIn({duration:a,easing:"linear"===
c?c:"swing",complete:d,queue:!1})},fadeOut:function(b,a,c,d){b.fadeOut({duration:a,easing:"linear"===c?c:"swing",complete:d,queue:!1})},fadeToggle:function(b,a,c,d){b.fadeToggle({duration:a,easing:"linear"===c?c:"swing",complete:d,queue:!1})},slideUp:function(b,a,c,d){b.slideUp({duration:a,easing:"linear"===c?c:"swing",complete:d,queue:!1})},slideDown:function(b,a,c,d){b.slideDown({duration:a,easing:"linear"===c?c:"swing",complete:d,queue:!1})},slideToggle:function(b,a,c,d){b.slideToggle({duration:a,
easing:"linear"===c?c:"swing",complete:d,queue:!1})},isAnimated:function(b){return b.is(":animated")}};var p={animate:function(b,a,d,p,e){d=d===c?250:d;h(b,"transition","all "+d+"ms "+(p||"linear"));k.capabilities.transform&&(p=g(a))&&h(b,"transform",m({top:p.top,left:p.left,scale:p.scale}));p=b.data("a-animate");p===c&&(p={running:0});p.running++;b.data("a-animate",p);l.delay(function(){l.each(a,function(a,c){b.css(c,a)});l.delay(function(){h(b,"transition","none");var a=b.data("a-animate");a.running--;
b.data("a-animate",a);e&&e()},d)},15)},fadeIn:function(b,a,c,d){var p=b.css("opacity")||1;b.css("opacity","0");b.show();this.animate(b,{opacity:p},a,c,function(){d&&d();b.css("opacity","")})},fadeOut:function(b,a,c,d){this.animate(b,{opacity:0},a,c,function(){d&&d();b.hide();b.css("opacity","")})},fadeToggle:function(b,a,c,d){(b.is(":visible")?this.fadeOut:this.fadeIn).call(this,b,a,c,d)},slideUp:function(b,a,c,d){b.css({height:b.innerHeight(),overflow:"hidden"});this.animate(b,{height:0},a,c,function(){d&&
d();b.hide();b.css({height:"",overflow:""})})},slideDown:function(b,a,c,d){var p=b.innerHeight();b.css({height:0,overflow:"hidden"});b.show();this.animate(b,{height:p},a,c,function(){d&&d();b.css({height:"",overflow:""})})},slideToggle:function(b,a,c,d){(b.is(":visible")?this.slideUp:this.slideDown).call(this,b,a,c,d)},isAnimated:function(b){b=b.data("a-animate");return b!==c&&0<b.running}};return k.capabilities.transition?p:e});"use strict";P.when("a-base","a-util","a-events","a-defer","p-detect").register("a-image",
function(e,l,k,h,m){function g(b){b=d(b);var a=b.data("a-dynamic-image");if(a&&"object"===typeof a){var c=b.data("a-dynamic-image-container");"undefined"===typeof c&&(c=b.closest(".a-dynamic-image-container"),0===c.length&&(c=b.parent()),b.data("a-dynamic-image-container",c));var n=window.devicePixelRatio?window.devicePixelRatio:1,p=c.width()*n,g=c.height()*n,e=Number.MAX_VALUE,h=Number.MAX_VALUE,k=b.attr("src")||"",m,z=p/g;l.each(a,function(b,a){var f=parseInt(b[0],10),c=parseInt(b[1],10),f=f-g,
c=c-p,c=1<=z?c:f;Math.abs(c)<h&&0<=c&&(h=Math.abs(c),m=a);Math.abs(c)<e&&(e=Math.abs(c),k=a)});m&&(k=m);f.schedule(k,b);f.fill();return k}}function c(){d("img.a-dynamic-image").each(function(){d(this).data("a-manual-replacement")||g(this)})}var d=e.$;d(window);var a=document.getElementsByTagName("img"),b={},p=function(){return{canLoad:function(){return!0},inFlight:0,limit:function(){return 2}}}(),f=function(){var a=[],f={};return{schedule:function(c,d){f[c]||(a.push(c),f[c]=!0);b[c]=b[c]||[];for(var n=
0;n<b[c].length;n++)if(d.is(b[c][n]))return;b[c].push(d)},fill:function(){if(p.canLoad())for(var b=0;b<p.limit()-p.inFlight;b++)if(0<a.length){var c=a.shift();f[c]=!1;n.load(c)}}}}(),n=function(){function c(a){var f=b[a];f&&0<f.length&&l.each(f,function(b){h.defer(function(){b.attr("src",a)})})}var n={};return{load:function(b){n[b]&&c(b);if(!1!==n[b]){var a=new Image;a.onload=function(){p.inFlight--;c(b);n[b]=!0;f.fill()};a.onerror=function(){p.inFlight--;n[b]=!1;f.fill()};p.inFlight++;h.defer(function(){a.src=
b})}},poll:function(){l.each(a,function(b){b=d(b);b.data("a-hires-loaded")||b.is(":hidden")||!l.onScreen(b)||b.data("a-manual-replacement")||(b.data("a-hires")&&f.schedule(b.data("a-hires"),b),b.data("a-hires-loaded",!0))})}}}();m.capabilities.hires&&k.on.ready(function(){l.interval(function(){n.poll();f.fill()},2E3)});k.on.ready(c);d(window).resize(c);return{loadHiResImage:function(b){var a=[];d(b).each(function(){var b=d(this),c=b.data("a-hires");c&&(f.schedule(c,b),f.fill(),a.push(c));b.data("a-hires-loaded",
!0)});return a},loadDynamicImage:function(b){var a=[];d(b).each(function(){a.push(g(this))});return a},loadImageManually:function(b,a){var f=[];d(b,a).each(function(){var b=d(this);if(!b.data("a-image-already-loaded")){b.data("a-image-already-loaded",!0);var a=g(b),c=d("<img>").attr("src",a||b.data("a-image-source"));f.push(a);var a=""+b.attr("class"),n=b.data("a-extra-classes");n&&(a+=" "+n);c.attr("class",a);c.attr("id",b.attr("id"));c.attr("style",b.attr("style"));c.data(b.data());b.replaceWith(c)}return f})},
loadDescendantImagesManually:function(b,a){var f=d(b,a).find("div.a-manually-loaded").filter(function(){return!d(this).data("a-image-already-loaded")});return this.loadImageManually(f)}}});"use strict";P.when("a-util","a-defer","a-base","a-events","a-declarative","a-state","a-ajax","a-animate","a-image","a-constants","p-detect","a-browser-events","a-preload").register("A",function(e){var l={};e.each(arguments,function(k){e.extend(l,k)});return l});"use strict";P.register("a-constants",function(e){return{constants:{keycodes:{BACKSPACE:8,
TAB:9,ENTER:13,ESCAPE:27,SPACE:32,LEFT_ARROW:37,UP_ARROW:38,RIGHT_ARROW:39,DOWN_ARROW:40,DELETE:46}}}});"use strict";P.when("jQuery","a-events","a-util","a-defer").register("a-browser-events",function(e,l,k,h){function m(){return window.orientation?window.orientation:d.width()>d.height()?90:0}function g(b){for(var f={},n=d,g,e;(e=b.pop())!==c;)g=a[e],a[e]="orientation"===e?m():n[e](),a[e]!==g&&(f[e]=g);return f}var c,d=e(window),a={height:d.height(),width:d.width(),scrollTop:0,scrollLeft:0,orientation:m()},
b={scroll:{timer:!1},resize:{timer:!1},orientationchange:{timer:!1}};d.bind("resize scroll orientationchange",function(d){var f=d.type,n;!1===b[f].timer&&(b[f].timer=k.delay(function(){b[f].timer=!1;n="scroll"===f?g(["scrollLeft","scrollTop"]):g(["height","width","orientation"]);n.orientation&&"resize"===f&&window.onorientationchange!==c&&(f="orientationchange");l.trigger(f,a,n)},100))});l.on.ready(function(){g(["scrollLeft","scrollTop","height","width","orientation"])});return{viewport:function(){return k.copy(a)}}});
"use strict";P.when("a-base","a-events").register("a-preload",function(e,l){function k(){if(0<a.length)c=a;else if(c=d,0===c.length||!b)return!1;if(r>=y)return!1;r++;return!0}function h(b,a){clearTimeout(a);r=1>r?0:r-1;w(b);t?p(x,0):x()}function m(b){if(b){var a=b.parentElement;a&&a.removeChild(b)}}function g(b,a){if("string"===typeof b)b=[b];else if("object"!==typeof b||null===b)return;var f,c;for(f=0;f<b.length;f++)(c=b[f])&&"string"!==typeof c?g(c,a):c&&" "!==c[0]&&a.splice(Math.round(Math.random()*
a.length),0,c)}var c=[],d=[],a=[],b=!1,p=setTimeout,f=document,n=f.documentElement,q=n.style,s=navigator,u="MozAppearance"in q,v=(q=!u&&"webkitAppearance"in q)&&0===s.vendor.indexOf("Apple"),t=!u&&!q&&0===s.appName.indexOf("Microsoft"),s=-1!==s.userAgent.indexOf("Mobile"),y=void 0!==window.plCount?window.plCount():!s&&(q||u)||t&&"object"===typeof XDomainRequest?5:2,r=0,w=function(b){u?setTimeout(function(){m(b)},5):m(b)},x=t||u||q?function(){if(k()){var b=c.pop(),a,d;if(u)a=f.createElement("object");
else if(v){var g=b.indexOf("?"),g=0<g?g:b.length,q=b.lastIndexOf(".",g);if(q)switch(b.substring(q+1,g).toLowerCase()){case "js":a=f.createElement("script");a.type="f";break;case "png":case "jpg":case "jpeg":case "gif":a=new Image}if(!a){h(b);return}}else a=new Image;a.onerror=function(){h(a,d)};a.onload=function(){h(a,d)};if(u||v&&"SCRIPT"===a.tagName)d=p(function(){h(a,d)},2500+100*Math.random());u?a.data=b:a.src=b;t||(a.width=a.height=0,a.style.display="none",n.appendChild(a));r<y&&x()}}:function(){};
l.on.afterLoad(function(){b=!0;x()});return{preload:function(b,a){a?a(b):(g(b,d),x())}}})})();
(function(){P.when("A","jQuery").register("a-touch-recognize",function(e,l){var k={tap:function(e,k){var g=0===e.deltaX&&0===e.deltaY&&150<e.duration,c=10>Math.abs(e.deltaX)&&10>Math.abs(e.deltaY)&&200<e.duration;if(g||c)return{name:"tap",touchFinished:!1}},doubleTap:function(h,k){var g=10>h.deltaX&&10>h.deltaY&&10>k.deltaX&&10>k.deltaY,c=300>e.now()-k.startTime,d=25>Math.abs(h.startX-k.startX)&&25>Math.abs(h.startY-k.startY),a=h.ended&&k.ended;if(g&&c&&d&&a)return{name:"doubleTap",touchFinished:!0}},
pan:function(e,k){if((250>=Math.abs(e.velocityX)&&250>=Math.abs(e.velocityY)||!e.ended)&&1<e.samples.length)return{name:"pan",direction:e.direction||Math.abs(e.deltaX)>Math.abs(e.deltaY)?"horizontal":"vertical"}},swipe:function(e,k){var g=e.samples[e.samples.length-1],c=Math.abs(g.x-e.startX),g=Math.abs(g.y-e.startY),d=250<Math.abs(e.velocityX)||250<Math.abs(e.velocityY),a=20<e.duration,b=e.samples&&2<e.samples.length;if(d&&(3<c||3<g)&&a&&b&&e.ended)return{name:"swipe",direction:e.direction||c>g?
"horizontal":"vertical",touchFinished:!0}}};return function(e,m){var g,c;for(c in k)if(k.hasOwnProperty(c)&&k[c]&&(g=k[c](e,m)))return g;return{name:"touch",touchFinished:!1}}});"use strict";P.when("A","jQuery","a-touch-recognize","ready").register("a-touch",function(e,l,k){function h(b,a,f){if(!b.multi&&(a=k(b,a),!b.finished)){f=b.samples[b.samples.length-1];f={x:f.x,y:f.y,direction:f.direction,targetX:f.x-b.targetOffset.left,targetY:f.y-b.targetOffset.top,deltaX:f.deltaX,deltaY:f.deltaY,velocityX:b.velocityX,
velocityY:b.velocityY,touchDeltaX:b.deltaX,touchDeltaY:b.deltaY,touchDuration:b.duration,ended:b.ended};var c=b.$triggerTarget;c.trigger(a.name,f);var d=b.direction||a.direction;d&&c.trigger(a.name+"-"+d,f);b.finished=a.touchFinished}}function m(b,a){var c,d;c=(b.pageX||b.x)-a.x;d=(b.pageY||b.y)-a.y;return"horizontal"===(g.direction?g.direction:Math.abs(c)>Math.abs(d)?"horizontal":"vertical")?0<c?"right":"left":0<d?"down":"up"}var g={},c={},d=null,a={touchstart:function(b,a,f,d){var q=null;f.hasClass("a-gesture-horizontal")?
q="horizontal":f.hasClass("a-gesture-vertical")&&(q="vertical");g={id:b.timeStamp,startTime:e.now(),startX:a.pageX,startY:a.pageY,deltaX:0,deltaY:0,velocityX:0,velocityY:0,duration:0,ended:!1,$target:f,$triggerTarget:d,targetOffset:f.offset(),targetWidth:f.innerWidth(),targetHeight:f.innerHeight(),multi:1<b.originalEvent.targetTouches.length,direction:q,capture:void 0,samples:[{x:a.pageX,y:a.pageY,deltaX:0,deltaY:0,elapsed:0,time:e.now()}]};h(g,c,b)},touchmove:function(b,a){if(g.samples&&g.samples.length){var f=
g.samples[g.samples.length-1],f={x:a.pageX,y:a.pageY,deltaX:a.pageX-f.x,deltaY:a.pageY-f.y,direction:m(a,f),elapsed:e.now()-g.startTime,time:e.now()};if(void 0===g.capture){var d=Math.abs(f.deltaX),q=Math.abs(f.deltaY);g.capture=!g.direction||"horizontal"===g.direction&&d>=q||"vertical"===g.direction&&q>=d}if(g.capture){b.preventDefault();g.samples.push(f);g.deltaX=a.pageX-g.startX;g.deltaY=a.pageY-g.startY;g.duration=f.elapsed;g.multi=g.multi||1<b.originalEvent.targetTouches.length;f=g.samples;for(d=
0;d<f.length;d++)q=f[d],100<e.now()-q.time&&1<f.length&&f.splice(d,1);for(var k=q=d=f=0,l=0,v=g.samples.length;l<v;l++)var t=g.samples[l],f=f+t.deltaX,d=d+t.deltaY,q=q+(t.elapsed-k),k=t.elapsed;g.velocityX=f/(q/1E3);g.velocityY=d/(q/1E3);h(g,c,b)}}},touchend:function(b,a){if(1<g.samples.length){var f=g.samples[g.samples.length-1],f={x:f.x,y:f.y,deltaX:f.deltaX,deltaY:f.deltaY,direction:m(f,g.samples[g.samples.length-2]),elapsed:e.now()-g.startTime,time:e.now()};g.samples.push(f);g.multi=g.multi||
1<b.originalEvent.targetTouches.length;g.duration=e.now()-g.startTime;g.ended=!0;h(g,c,b)}else g.multi=g.multi||1<b.originalEvent.targetTouches.length,g.duration=e.now()-g.startTime,g.ended=!0;c=g},touchcancel:function(b,a){g.multi=g.multi||1<b.originalEvent.targetTouches.length;g.duration=e.now()-g.startTime;g.ended=!0;c=g}};l(document.body).delegate(".a-gesture","mouseenter mouseleave",function(b){b.preventDefault()});l(document.body).delegate(".a-gesture","touchstart touchend touchmove touchcancel",
function(b){var c=l(this);c.data("a-touch-bound")||(c.data("a-touch-bound",!0),c.bind("touchstart touchend touchmove touchcancel",function(b){a[b.type](b,b.originalEvent.targetTouches[0],l(this),l(b.target))}),a[b.type](b,b.originalEvent.targetTouches[0],c,l(b.target)))});l(window).bind("touchstart touchmove",function(){clearTimeout(d);e.pauseDeferred();d=e.delay(function(){e.executeDeferred()},100)});return{pauseTouchEvents:function(b){l(window).bind("touchstart.a-pause touchmove.a-pause touchend.a-pause",
function(b){b.preventDefault()});e.delay(function(){l(window).unbind("touchstart.a-pause touchmove.a-pause touchend.a-pause")},b)}}});"use strict";P.when("A","a-touch","p-detect").register("a-touch-scroll",function(e,l,k){function h(b,a){b.css("-webkit-transform","translate3d(0,"+a+"px, 0)")}function m(b,a,c,d){b.css("-webkit-transition",c?"-webkit-transform "+a+" "+(d?d:"ease-out"):"none")}function g(c,f,d){b=!1;e.pauseDeferred();m(c,"0.0s",!1);a+=f.deltaY;a=Math.min(d.max,a);a=Math.max(d.min,a);
h(c,a);e.executeDeferred()}function c(c,f,d){e.pauseDeferred();var g=a;a+=f.velocityY;a=Math.min(d.max,a);a=Math.max(d.min,a);Math.abs(g-a);m(c,"0.5s",!0,!1);h(c,a);b=!0;c.one("webkitTransitionEnd",function(){b=!1;e.executeDeferred()})}var d=e.$,a=0,b=!1;k.capabilities.touchScrolling||(d(document.body).delegate(".a-gesture.a-scroll-inner","touchstart",function(a){var c=d(this);if(b){var n=c.css("-webkit-transform").split(", ")[5].slice(0,-1);b=!1;m(c,"0",!1);h(c,n);a.preventDefault();a.stopImmediatePropagation()}}),
d(document.body).delegate(".a-gesture.a-scroll-inner","pan-vertical swipe-vertical",function(b,a){var n=a.ended?c:g,e;e=d(this);e={max:0,min:e.innerHeight()<e.parent().innerHeight()?0:-1*(e.innerHeight()-e.parent().innerHeight())};n(d(this),a,e)}))});"use strict";P.when("A").register("a-immersive-image",function(e){function l(c,a){var b=a?"-webkit-transform 0.5s ease-out":"none";c.css("-webkit-transition",b);c.parent().css("-webkit-transition",b)}function k(c,a,b,e){a="translate("+a+"px, "+b+"px)";
c.css("-webkit-transform","scale("+e+")");c.parent().css("-webkit-transform",a)}function h(c,a,b,e){var f=c.innerWidth()/3*e;c=c.innerHeight()/3*e;e=a&&a/Math.abs(a);var n=b&&b/Math.abs(b),g=Math.abs(a)>f?f*e:a,k=Math.abs(b)>c?c*n:b;return{x:g,y:k,boundX:Math.abs(a)>f,boundY:Math.abs(b)>c,signX:e,signY:n}}function m(c,a,b,g){a.zoomed&&(e.trigger("a:immersiveImage:zoomOut",{$image:c,immersiveImage:a}),k(c,0,0,1),l(c,b),a.atBounds=!1,a.zooming=!0,a.scale=1,e.delay(function(){c.css("-webkit-backface-visibility",
"hidden");g&&(a.zooming=!1,a.zoomed=!1)},600))}function g(d,a,b,g,f){a.zoomed||(e.trigger("a:immersiveImage:zoomIn",{$image:d,immersiveImage:a}),d.css("-webkit-backface-visibility","visible"),l(d,!0),c(d,a,b,g,3),a.atBounds=!1,a.zooming=!0,e.delay(function(){f&&(a.zooming=!1,a.zoomed=!0)},600))}function c(c,a,b,e,f){var n=c.innerWidth()/2,g=c.innerHeight()/2;b=h(c,(n-b)*f,(g-e)*f,f);a.offsetX=b.x;a.offsetY=b.y;a.scale=f;k(c,a.offsetX,a.offsetY,f)}e.declarative("a-immersive-image",["touchstart"],function(c){var a=
c.$target;if("IMG"===a.prop("tagName")&&!a.data("a-immersive-init")){var b={zoomed:!1,atBounds:!1,offsetX:0,offsetY:0,scale:1};a.data("a-immersive-image",b);a.bind("doubleTap",function(c,f){b.zooming||(b.zoomed?m(a,b,!0,!0):g(a,b,f.targetX,f.targetY,!0))});a.bind("pan swipe",function(c,f){if(b.zoomed&&!b.zooming){var d=f.ended?f.deltaX+f.velocityX/b.scale:f.deltaX,e=f.ended?f.deltaY+f.velocityY/b.scale:f.deltaY,g=f.ended;f.ended&&(b.atBounds=!1);var m=f.ended,d=h(a,b.offsetX+d,b.offsetY+e,b.scale);
b.offsetX=d.x;b.offsetY=d.y;b.endedAtBounds&&d.boundX&&d.signX===b.signX&&(b.atBounds=!0);b.endedAtBounds=d.boundX&&m;b.signX=d.signX;l(a,g);k(a,b.offsetX,b.offsetY,b.scale)}});(function(){function c(b,a){var f=b[0].pageX-a.left,d=b[0].pageY-a.top,e=b[1].pageX-a.left,g=b[1].pageY-a.top;return{midX:(f+e)/2,midY:(d+g)/2,distance:Math.sqrt(Math.pow(f-e,2)+Math.pow(d-g,2))}}var f,d=0,e=!1;a.bind("touchstart",function(b){var d=b.originalEvent.targetTouches;2===d.length&&(f=c(d,a.offset()),b.stopImmediatePropagation(),
b.preventDefault())});a.bind("touchmove",function(k){var h=k.originalEvent.targetTouches;if(2===h.length&&(h=c(h,a.offset()),f)){e=!0;var l=h.distance-f.distance;d+=Math.abs(l);4<d&&!b.zooming&&(0>l?m(a,b,!0,!1):g(a,b,h.midX,h.midY,!1));k.stopImmediatePropagation();k.preventDefault()}});a.bind("touchend touchleave touchcancel",function(a){e&&0===a.originalEvent.targetTouches.length&&(d=0,e=!1,b.zoomed=1<b.scale,b.zooming=!1);b.atBounds=!1;a.preventDefault()})})();a.data("a-immersive-init",!0)}});
return{zoomOut:function(c){var a=c.data("a-immersive-image");a&&m(c,a,!1,!0)}}})})();
(function(){P.when("A").register("a-popover-util",function(e){var l=e.$;return{eventOccursWithin:function(e,h){return 0<l(e.target).closest(h).length},trigger:function(k,h){e.trigger("a:popover:"+k,{popover:h});h.name&&e.trigger("a:popover:"+k+":"+h.name,{popover:h})}}});"use strict";P.when("A").register("a-popover-position",function(e){function l(c,d){var a=c.outerHeight(!0),b=c.outerWidth(!0),e=c.offset(),f=d.offset(),g,q;g=d[0];g.getBoundingClientRect?(q=g.getBoundingClientRect(),g=q.right-q.left,
q=q.bottom-q.top):(g=d.width(),q=d.height());return{popoverHeight:a,popoverWidth:b,popoverLeft:e.left,popoverTop:e.top,popoverRight:e.left+b,popoverBottom:e.top+a,popoverVerticalCenter:e.top+a/2,popoverHorizontalCenter:e.left+b/2,triggerHeight:q,triggerWidth:g+1,triggerLeft:f.left-1,triggerTop:f.top-1,triggerRight:f.left+g+1,triggerBottom:f.top+q+1,triggerVerticalCenter:f.top+q/2,triggerHorizontalCenter:f.left+g/2,windowHeight:window.innerHeight?window.innerHeight:m.height(),windowWidth:window.innerWidth?
window.innerWidth:m.width(),windowTop:m.scrollTop(),windowLeft:m.scrollLeft(),windowRight:m.scrollLeft()+m.width(),windowBottom:m.scrollTop()+m.height()}}function k(c,d,a,b,e){c=c.find(".a-popover-inner");b>e&&e<a.popoverHeight?(d.top=b<a.popoverHeight?a.triggerBottom-b:a.triggerBottom-a.popoverHeight,c.css({height:b<a.popoverHeight?b+"px":"auto","overflow-y":a.popoverHeight>b?"scroll":"visible"})):(d.top=a.triggerTop,c.css({height:e<a.popoverHeight?e+"px":"auto","overflow-y":a.popoverHeight>e?"scroll":
"visible"}));return d}function h(c){return c.removeClass("top bottom left right")}e=e.$;var m=e(window),g={windowCenter:function(c,d){var a=l(c,d),b={};b.top=a.windowHeight/2+a.windowTop-a.popoverHeight/2;b.left=a.windowWidth/2-a.popoverWidth/2;return b},windowTop:function(c,d){var a=l(c,d),b={top:0};b.left=a.windowWidth/2-a.popoverWidth/2;return b},windowFullWidth:function(c,d){return{top:0,left:0}},triggerRight:function(c,d){var a=l(c,d),b={};b.top=a.triggerVerticalCenter-a.popoverHeight/2;b.left=
a.triggerRight;h(c).addClass("right");return b},triggerLeft:function(c,d){var a=l(c,d),b={};b.top=a.triggerVerticalCenter-a.popoverHeight/2;b.left=a.triggerLeft-a.popoverWidth;h(c).addClass("left");return b},triggerTop:function(c,d){var a=l(c,d),b={};b.top=a.triggerTop-a.popoverHeight;b.left=a.triggerHorizontalCenter-a.popoverWidth/2;h(c).addClass("top");return b},triggerBottom:function(c,d){var a=l(c,d),b={};b.top=a.triggerBottom;b.left=a.triggerHorizontalCenter-a.popoverWidth/2;h(c).addClass("bottom");
return b},triggerHorizontal:function(c,d){var a=l(c,d),b={};a.triggerLeft-a.windowLeft>a.popoverWidth+20?(b.top=a.triggerVerticalCenter-a.popoverHeight/2,b.left=a.triggerLeft-a.popoverWidth,h(c).addClass("left")):(b.top=a.triggerVerticalCenter-a.popoverHeight/2,b.left=a.triggerRight,h(c).addClass("right"));return b},triggerVertical:function(c,d){var a=l(c,d),b={};a.triggerTop-a.windowTop>a.popoverHeight+20?(b.top=a.triggerTop-a.popoverHeight,b.left=a.triggerHorizontalCenter-a.popoverWidth/2,h(c).addClass("top")):
(b.top=a.triggerBottom,b.left=a.triggerHorizontalCenter-a.popoverWidth/2,h(c).addClass("bottom"));return b},triggerVerticalAlignLeft:function(c,d){var a=l(c,d),b={};b.top=a.windowBottom-a.triggerBottom>a.popoverHeight?a.triggerBottom+3:a.triggerTop-a.popoverHeight-3;b.left=a.triggerLeft;return b},triggerNativeDropdown:function(c,d){var a=c.find(".a-popover-inner");a.css({"min-width":"0px",width:"auto",height:"auto"});var b=l(c,d),e=50<b.windowWidth-(b.triggerLeft+b.popoverWidth)?g.triggerNativeDropdownLeft(c,
d,b):g.triggerNativeDropdownRight(c,d,b);"scroll"===a.css("overflow-y")&&-1<navigator.userAgent.indexOf("MSIE")?(b=Math.max(b.popoverWidth,b.triggerWidth)+15,a.width(b)):a.css("min-width",b.triggerWidth+"px");return e},triggerNativeDropdownRight:function(c,d,a){a||(a=l(c,d));d={};var b=a.triggerTop-a.windowTop,e=a.windowBottom-a.triggerBottom;d.left=a.triggerRight-a.popoverWidth+2;return k(c,d,a,b,e)},triggerNativeDropdownLeft:function(c,d,a){a||(a=l(c,d));d={};var b=a.triggerTop-a.windowTop,e=a.windowBottom-
a.triggerBottom;d.left=a.triggerLeft;return k(c,d,a,b,e)}};return g});"use strict";P.when("A","ready").register("a-popover-iframes",function(e){function l(){h++;var c=document.createElement("iframe");c.src="javascript:false;";c.id="a-popover-iframe-"+h;c.className="a-popover-iframe";c.style.cssText="width: 0; height: 0; border: 0; opacity: 0; filter: alpha(opacity = 0); zoom: 1; display: none; position: absolute;";c.frameborder="0";c.tabindex="-1";document.body.appendChild(c);return k(c)}var k=e.$;
k("body");var h=0,m=[],g=[];e.on.ready(function(){m.push(l())});return{get:function(){var c=0===m.length?l():m.shift();g.push(c);return c},release:function(c){c.hide();e.each(g,function(d,a){c.is(d)&&g.splice(1,a)});m.push(c)}}});"use strict";P.when("A","a-popover-util").register("a-popover-ajax",function(e,l){function k(e){e.update('<div class="a-popover-loading-wrapper a-text-center"><div class="a-box a-color-base-background a-popover-loading"></div></div>');e.show();e.updatePosition()}return{update:function(h,
m,g){var c=g.timeout||5E3,d=g.ajaxFailMsg||"Sorry, content is not available.";g=g.cache;var a=setTimeout(function(b){return function(){k(b)}}(h),100);e.ajax(m,{type:"GET",timeout:c,cache:g,success:function(b){clearTimeout(a);l.trigger("ajaxSuccess",h);h.update(b);h.show();h.updatePosition()},error:function(){clearTimeout(a);l.trigger("ajaxFail",h);h.update(d);h.show();h.updatePosition()}})},showSpinner:k}});"use strict";P.when("A","ready").register("a-popover-navigate",function(e){function l(c){"string"===
typeof c&&(m=!0,window.location.hash=c);return window.location.hash||""}var k=e.$,k=k(window),h=[],m=!1,g={};h.push(l());k.bind("hashchange",function(c){c.preventDefault();h.push(l());32<=h.length&&h.shift();m?m=!1:e.trigger("a:popover:navigate",g[h[h.length-1]])});return{forward:function(c,d){c=c+"?"+e.now();g["#"+c]=d;l(c)},back:function(){0<h.length&&h.pop();window.history.back()}}});"use strict";P.when("A","a-popover-iframes","a-popover-position","ready").register("a-popover-manager",function(e,
l,k){var h=e.$,m=h("body");h(window);var g=0,c={};return{create:function(d){g++;var a=g.toString();d=h(d).attr("id","a-popover-"+a).data("a-popover-id",g);d.css("display","none");m.append(d);d={id:a,$popover:d};return c[a]=d},destroy:function(d){var a=c[d];a.$popover.remove();a.$iframe.hide();delete c[d]},get:function(d){return c[d]}}});"use strict";P.when("A","a-popover-manager","a-popover-iframes","a-popover-position","a-popover-ajax","a-popover-util","a-popover-navigate","ready").register("a-popover-base",
function(e,l,k,h,m,g,c){function d(b){b=f("#a-popover-"+b);b.remove();if(b.length){b=b[0];for(var a=document.createDocumentFragment();b.firstChild;)a.appendChild(b.firstChild);return a}return!1}function a(a,p){var h=a.$trigger;if(h){var r=h.data("a-popover-id"),w=n[r];if(w)if(w.$popover.is(":hidden"))delete n[r];else return;a.content||a.url||(a.preloaded=!0);a.name&&(r=q[a.name]?q[a.name].id:null);r=r?l.get(r):f.extend(l.create(a.skin(a.content||"",a)),u,a);if(!r.animating)return r.preloaded&&(w=
d(r.name))&&r.update(w),r.data=a.data,g.trigger("beforeShow",r),h.data("a-popover-id",r.id),r.$trigger=h,r.$iframe=k.get(),a.url&&m.update(r,a.url,a),r.alone&&e.each(n,function(a){a.$popover.hide();b(a.id)}),r.name&&r.navigate&&!p&&c.forward(r.name,r.$trigger),r.name&&(q[r.name]=r),a.url||(g.trigger("show",r),r.show(),r.updatePosition()),n[r.id]=r,s.push(r),r}}function b(b,a){b="object"===typeof b?b.data("a-popover-id"):b;var f=n[b];f&&!f.animating&&(f.name&&f.navigate&&!a&&c.back(),k.release(f.$iframe),
g.trigger("hide",f),f.hide(),delete n[b],s.pop())}function p(b){if("string"===typeof b)return q[b];b="object"===typeof b?b.data("a-popover-id"):b;return n[b]}var f=e.$;f(window);var n={},q={},s=[],u={modal:!1,alone:!0,animating:!1,position:"triggerVertical",updatePosition:function(){var b=this.$popover,a=this.$iframe,c=h[this.position](b,this.$trigger);b.offset(c);a.height(b.height()).width(b.width());a.css("z-index",parseInt(b.css("z-index"),10)-1);a.show().offset({top:c.top+8,left:c.left+8});g.trigger("positionUpdated",
this)},ajax:function(b,a){m.update(this,b,a)},show:function(){this.animating=!0;this.$popover.show();this.animating=!1},hide:function(){this.animating=!0;this.$popover.hide();this.animating=!1}};f(document).bind("touchstart click",function(a){f(a.target);e.each(n,function(c){g.eventOccursWithin(a,c.$trigger)||g.eventOccursWithin(a,c.$popover)||b(c.id)})});e.on("resize",function(){e.each(n,function(b){b.updatePosition()})});e.declarative("a-popover-close",["click"],function(a){var c=a.$target.closest(".a-popover").data("a-popover-id"),
f=l.get(c);b(c);g.trigger("dismiss",f);a.$event.preventDefault()});e.on("a:popover:navigate",function(c){c?a({$trigger:c},!0):(c=s[s.length-1])&&b(c.id,!0)});return{show:a,hide:b,get:p,remove:function(a){var c=p(a);c&&(b(a),l.destroy(c.id),delete q[a])}}});"use strict";P.when("A","a-popover-base","a-popover-util").register("a-tooltip",function(e,l,k){function h(d){var a=d.data;(d=l.show({$trigger:d.$declarativeParent,skin:g,update:c,data:a.data,alone:!1,content:d.data.content,position:a.position||
"triggerVertical",hide:function(){var b=this;b.animating=!0;e.fadeOut(this.$popover,250);e.delay(function(){b.animating=!1},125)}}))&&d.destroyTimer&&(clearTimeout(d.destroyTimer),d.destroyTimer=null)}function m(c){var a=c.$declarativeParent;if(c=l.get(a))c.destroyTimer=e.delay(function(){l.hide(a)},125)}var g=function(c){return['<div class="a-tooltip">','<div class="a-tooltip-inner">'+c+"</div>",'<div class="a-arrow-border">\n<div class="a-arrow"></div>\n</div>\n</div>'].join("\n")},c=function(c){this.$popover.find(".a-tooltip-inner").html(c)};
e.capabilities.touch?e.declarative("a-tooltip","click",h):(e.declarative("a-tooltip","mouseenter",h),e.declarative("a-tooltip","mouseleave",m))});"use strict";P.when("A","a-popover-base").register("a-popover",function(e,l){var k=e.$,h=function(c){return function(d){return['<div class="a-popover">\n<div class="a-popover-wrapper">\n<div class="a-popover-header">',"<h4>"+c+"</h4>",'<button data-action="a-popover-close" class="a-button-close a-declarative">\n<i class="a-icon a-icon-close"></i>\n</button>\n</div>',
'<div class="a-popover-inner">'+d+"</div>",'<div class="a-arrow-border">\n<div class="a-arrow"></div>\n</div>\n</div>\n</div>'].join("\n")}},m=function(c){k(".a-popover-inner",this.$popover).html(c)},g={click:function(c,d){l.show({$trigger:c.$declarativeParent,skin:h(d.header),content:d.content,url:d.url,update:m,data:d.data,name:d.name,position:d.position||"triggerVertical",hide:function(){var a=this;a.animating=!0;e.fadeOut(this.$popover,250);e.delay(function(){a.animating=!1},250)}})}};e.declarative("a-popover",
["click"],function(c){g[c.type](c,c.data);c.$event.preventDefault()})});"use strict";P.when("A","a-popover-base").register("a-modal",function(e,l){var k=e.$;k("body").append('<div id="a-popover-modal" />');var h=function(c,d){var a=d.header||"",b=d.footer,e=d.width,f=d.height,b=b?['<div class="a-popover-footer">',b,"</div>"].join("\n"):"";return['<div class="a-popover a-popover-modal">\n<div class="a-popover-wrapper"',e||f?['style="',f?"height:"+f+"px;":"",e?"width:"+e+"px;":"",'"'].join("\n"):"",
'>\n<div class="a-popover-header">',"<h4>"+a+"</h4>",'<button data-action="a-popover-close" class="a-button-close a-declarative">\n<i class="a-icon a-icon-close"></i>\n</button>\n</div>\n<div class="a-popover-inner">',c,"</div>",b,'<div class="a-arrow-border">\n<div class="a-arrow"></div>\n</div>\n</div>\n</div>'].join("\n")},m=function(c){"string"===typeof c?k(".a-popover-inner",this.$popover).html(c):c&&k(".a-popover-inner",this.$popover).html("").append(c)},g={click:function(c,d){l.show({$trigger:c.$declarativeParent,
position:"windowCenter",modal:!0,header:d.header,footer:d.footer,content:d.content,width:d.width,height:d.height,url:d.url,ajaxFailMsg:d.ajaxFailMsg,cache:"false"===d.cache||!1===d.cache?!1:!0,name:d.name,data:d.data,skin:h,update:m,show:function(){this.animating=!0;this.$popover.show();k("#a-popover-modal").show();this.animating=!1},hide:function(){var a=this;a.animating=!0;e.fadeOut(this.$popover,250);k("#a-popover-modal").hide();e.delay(function(){a.animating=!1},250)}})}};e.declarative("a-modal",
["click"],function(c){g[c.type](c,c.data);c.$event.preventDefault()})});"use strict";P.when("A","jQuery","a-popover-base","a-popover-util").register("a-dropdown",function(e,l,k,h){function m(b,a){var c=document.createElement("ul"),d=l('<li tabIndex="0" role="option" />'),e=b.data("aCssClass"),g=b.data("aId"),k=b.data("aImageSource"),h=null,m=l('<a tabIndex="-1" />').attr({href:"javascript:void(0)","data-value":b.val()}).append(b.text());a&&m.addClass("a-active").attr("aria-selected","true");e&&d.addClass(e);
g&&d.attr("id",g);k&&(m.addClass("a-option-has-image"),h=l("<img>").attr({src:k,"class":"a-rich-option-image"}));c.appendChild(d.append(m.prepend(h))[0]);return c.innerHTML}function g(b){var a;a=b.data("a-has-images")?['<ul tabIndex="-1" class="a-nostyle a-list-link a-box-list" role="listbox" aria-multiselectable="false">']:['<ul tabIndex="-1" class="a-nostyle a-list-link" role="listbox" aria-multiselectable="false">'];var c=b.children("optgroup,option:not(.a-prompt)"),d=!1,e=b.val();c.each(function(){var b=
l(this);b.is("optgroup")?(b.children().each(function(){a.push(m(l(this),this.selected||e===this.value))}),a.push('<li tabIndex="-1" class="divider"><hr /></li>'),d=!0):(d=!1,a.push(m(b,this.selected||e===this.value)))});d&&a.pop();a.push("</ul>");return a.join("\n")}function c(b,a,c){c.hasClass("a-button-disabled")||(b=k.show({$trigger:b.$declarativeParent,content:a,skin:function(b){return['<div class="a-popover a-dropdown">\n<div class="a-popover-wrapper">\n<div class="a-popover-inner">',g(b),"</div>\n</div>\n</div>"].join("\n")},
position:"triggerNativeDropdown",sourceSelect:a,sourceButton:c,name:a[0].name}))&&c.data("popover",b).data("isPressed",!0)}function d(b){try{b.$event.preventDefault()}catch(a){}var f=b.$target.closest(".a-button-dropdown");if(f.data("isPressed"))k.hide(f.data("popover").$popover);else{var d=f.prevAll("select").eq(0);c(b,d,f)}}function a(b,c){if(b&&(c||""===c)){var f=l("select#"+b);if(0===f.length)throw Error("Invalid ID passed to a-dropdown.setValue: "+a);var d=-1,e=f[0];if(""===c)d=0;else for(d=
e.options.length;d--&&e.options[d].value!==c;);if(-1<d)return f=f.nextAll(".a-button-dropdown"),e.options[d].selected=!0,f.length&&(k.remove(e.name),f.data("isPressed",!1),f.find(".a-dropdown-prompt").html(e.options[d].innerHTML),f.css("min-width",d/e.options.length+"%")),!0}return!1}e.declarative("a-dropdown-button","click",function(b){b.$target.closest(".a-button-dropdown").data("isPressed")||d(b)});e.declarative("a-dropdown-button","keydown",function(b){if(!b.$target.closest(".a-button-dropdown").data("isPressed")){var a=
e.constants.keycodes,c=b.$event.which;c!==a.DOWN_ARROW&&c!==a.ENTER&&c!==a.SPACE||d(b)}});l(document).delegate(".a-popover.a-dropdown a","click",function(){var b=l(this),a=b.data("value"),c=k.get(b.closest(".a-popover"));c.sourceSelect.val()!==a&&(c.sourceSelect.val(""+a),c.sourceSelect.trigger("change",[b]));k.hide(c.id)}).delegate(".a-native-dropdown","change",function(b,a){var c=l(this).nextAll(".a-button-dropdown"),d="",g=this.options.length,k;if(c.length){for(c=c.eq(0);g--;)if(k=this.options[g],
k.value===this.value){d=k.innerHTML;k.selected=!0;break}else k.selected=!1;"undefined"===typeof a&&(g=c.data("popover"))&&(a=g.$popover.find('a[data-value="'+this.value+'"]'));(g=a)&&g.length&&g.addClass("a-active").prop("aria-selected",!0).closest("ul").find("a").not(g).prop("aria-selected",!1).removeClass("a-active");k=this.name;var h=this.value;k&&""!==k&&e.trigger("a:dropdown:selected:"+k,{auiItemNode:g&&g.length?g[0]:null,nativeItemNode:this.options[this.selectedIndex],selectNode:this,name:k,
value:h});c.find(".a-dropdown-prompt").html(d)}}).delegate(".a-button-text","focusin",function(){var b=l(this).closest(".a-button");b.hasClass("a-button-disabled")||b.addClass("a-button-focus")}).delegate(".a-button-text","focusout",function(){l(this).closest(".a-button").removeClass("a-button-focus")}).delegate(".a-button-dropdown:not(.a-button-disabled)","focusin",function(){l(this).find(".a-button-text").focus()}).delegate(".a-dropdown li","keydown",function(b){var a=l(this),c=e.constants.keycodes;
switch(b.which){case c.UP_ARROW:b.preventDefault();a.prev().focus();break;case c.DOWN_ARROW:b.preventDefault();a.next().focus();break;case c.ENTER:case c.SPACE:b.preventDefault();a.find("a").trigger("click");break;case c.ESCAPE:b.preventDefault(),b=k.get(a.closest(".a-popover")),b.sourceButton.find(".a-button-text").focus(),k.hide(b.id)}});e.on("a:popover:show",function(b){var a=b.popover.$trigger,c=a.closest(".a-button-dropdown");if(c.length&&c.is(":visible")){c=b.popover.id+"_dropdown_combobox";
b=b.popover.$popover;var d=b.find(".a-active");a.attr("aria-pressed",!0).attr("aria-owns",c);b.find("ol,ul").eq(0).attr("id",c);d.length?d.closest("li").focus():b.find("li").first().focus()}});e.on("a:popover:hide",function(b){var a=b.popover.$trigger,c=a.closest(".a-button-dropdown");c.length&&c.is(":visible")&&(a.attr("aria-pressed",!1),c.data("isPressed",!1).focus(),b.popover.$popover.css("width","auto"))});return{updateOption:function(b,c){if(b&&""!==b){var d=l("option#"+b);if(0===d.length)throw Error("Invalid ID passed to dropdown.updateOption: "+
b);if(c){var e=d.closest("select"),g=e.nextAll(".a-button-dropdown"),h=d[0];k.remove(e[0].name);g.data("isPressed",!1);c.value&&d.val(c.value);void 0!==c.selected&&(!h.selected&&c.selected?a(e[0].id,h.value):h.selected&&!c.selected&&a(e[0].id,""));c.image_source&&d.data("a-image-source",c.image_source);c.native_css_class&&(h.className=c.native_css_class);c.css_class&&d.data("a-css-class",c.css_class);c.native_id&&(h.id=c.native_id);c.id&&d.data("a-id",c.id);c.text&&(d.text(c.text),h.selected&&a(e[0].id,
h.value))}}},updateSelect:function(b,a){if(b&&""!==b){var c={none:!0,micro:!0,mini:!0,small:!0,base:!0,medium:!0,large:!0,"extra-large":!0,"double-large":!0,block:!0},d=l("select#"+b);if(0===d.length)throw Error("Invalid ID passed to a-dropdown.updateSelect: "+b);if(a){var e=d[0],g=d.nextAll(".a-button-dropdown"),h=g[0],m=d.siblings("label");k.remove(e.name);g.data("isPressed",!1);a.name&&(e.name=a.name);if(a.option_prompt){var t=d.find(".a-prompt");t.length?(t.text(a.option_prompt),t.prop("selected")&&
g.find(".a-dropdown-prompt").text(a.option_prompt)):(d.prepend(l("<option class='a-prompt' />").text(a.option_prompt)),g.find(".a-dropdown-prompt").text(a.option_prompt))}void 0!==a.has_images&&d.data("a-has-images",!!a.has_images);void 0!==a.button_size&&g.length&&("small"===a.button_size?g.addClass("a-button-small"):g.removeClass("a-button-small"));void 0!==a.spacing&&c.hasOwnProperty(a.spacing)&&(c=/\ba-spacing-[a-z]+\b/g,e.className=e.className.replace(c,""),h.className=h.className.replace(c,
""),d.addClass("a-spacing-"+a.spacing),g.addClass("a-spacing-"+a.spacing));void 0!==a.grid_units&&(c=/\ba-button-span\d{1,2}\b/g,e.className=e.className.replace(c,""),h.className=h.className.replace(c,""),isFinite(a.grid_units)&&0<a.grid_units&&13>a.grid_units&&(d.addClass("a-button-span"+a.grid_units),g.addClass("a-button-span"+a.grid_units)));a.width_name&&("base"===a.width_named?g.addClass("a-button-width-normal"):g.removeClass("a-button-width-normal"));a.status&&("disabled"===a.status?(e.disabled=
!0,g.addClass("a-button-disabled")):(e.disabled=!1,g.removeClass("a-button-disabled")));a.native_id&&(e.id=a.native_id,m.length&&(m[0].htmlFor=a.native_id));a.id&&(h.id=a.id);a.native_css_class&&((h=d.data("a-native-class"))&&d.removeClass(h),d.addClass(a.native_css_class).data("a-native-class",a.native_css_class));a.css_class&&((h=g.data("a-class"))&&g.removeClass(h),g.addClass(a.css_class).data("a-class",a.css_class));void 0!==a.label_text&&(""===a.label_text?(g.find(".a-dropdown-label").remove(),
d.siblings("label").remove()):(h=g.find(".a-dropdown-label"),h.length?h.text(a.label_text):g.find(".a-dropdown-prompt").before(l("<span class='a-dropdown-label' />").text(a.label_text)),m.length?m.text(a.label_text):d.before(l("<label for='"+e.id+"' class='a-native-dropdown' />").text(a.label_text))),g.css("min-width",""===a.label_text?"0.1%":"0%"))}}},setValue:a}});"use strict";P.when("A","a-popover-base","a-popover-util","a-touch","p-detect").register("a-secondary-view",function(e,l,k,h,m){function g(a,
b){a.css("-webkit-transition",b?"-webkit-transform 400ms ease-in-out":"none")}function c(a,b,c){a.css("-webkit-transform",e.capabilities.transform3d?"translate3d("+b+"px,"+c+"px, 0)":"translate("+b+"px,"+c+"px)")}function d(a){f=a.originalEvent.targetTouches[0].pageY}function a(a){var c=a.originalEvent.targetTouches[0],d=b(a.target).closest(".a-scroll-inner"),e=d.closest(".a-scroll"),g=m.capabilities.touchScrolling,c=f-c.pageY;g||a.preventDefault();g&&!d.length&&a.preventDefault();g&&d.length&&(0>=
e.scrollTop()&&1>c&&a.preventDefault(),e.scrollTop()+e.prop("offsetHeight")>=e.prop("scrollHeight")&&1<c&&a.preventDefault())}var b=e.$,p=b(window);b("body");var f=0,n=function(a,b,c,d,f){"undefined"===typeof d&&(d=!0);return function(e){return['<div class="a-popover a-popover-secondary'+(f?" a-popover-no-header":"")+'">','<div class="a-popover-wrapper">\n<div class="a-popover-header">\n<div class="a-row">\n<div class="a-span4">\n<i class="a-icon a-icon-page-back"></i>\n<a class="a-declarative" data-action="a-popover-close" href="#"><h4>',
b,'</h4></a>\n</div>\n<div class="a-span8 a-span-last a-text-right">\n<h4>',a,"</h4>\n</div>\n</div>\n</div>",'<div class="a-popover-inner'+(d?" a-scroll":"")+(c?" a-color-alternate-background":"")+'">','<div class="'+(d?"a-gesture a-scroll-inner":"")+'">','<div class="a-popover-header-spacing"></div>\n<div class="a-container a-secondary-view-inner">',e,"</div>\n</div>\n</div>\n</div>\n</div>"].join("\n")}},q=function(a){var c=b(".a-secondary-view-inner",this.$popover);"string"===typeof a?c.html(a):
a&&c.html("").append(a);c.parent().css("-webkit-transition","none");c.parent().css("-webkit-transform","translateY(0)")},s={click:function(b,f){var m=f.disableAnimation?0:410;l.show({$trigger:b.$declarativeParent,$declarativeParent:b.$declarativeParent,content:f.content,skin:n(f.header,f.backButtonText||"Back",f.alternateBackground,f.scrollable,f.hideHeader),url:f.url,update:q,data:f.data,name:f.name,navigate:!0,position:"windowFullWidth",show:function(){function b(){e.pauseDeferred();n.animating=
!0;c(q,0,window.scrollY);q.height(window.innerHeight);q.width(window.innerWidth);e.delay(function(){n.scrollTop=window.scrollY;n.animating=!1;e.executeDeferred()},m)}var n=this,q=n.$popover;n.animating=!0;e.pauseDeferred();h.pauseTouchEvents(m);k.trigger("beforeSlide",n);c(q,window.innerWidth,window.scrollY);q.height(window.innerHeight);q.width(window.innerWidth);f.disableAnimation||g(q,!0);q.show();e.delay(function(){c(q,0,window.scrollY)},0);p.bind("touchstart.a-secondary-view",d);p.bind("touchmove.a-secondary-view",
a);n.scrollTop=window.scrollY;e.delay(function(){e.delay(function(){p.bind("scroll.a-secondary-view",b);p.bind("resize.a-secondary-view",b)},m);k.trigger("afterSlide",n);n.animating=!1;e.executeDeferred()},m)},hide:function(){var a=this,b=a.$popover,d=a.$iframe;p.unbind("scroll.a-secondary-view");p.unbind("resize.a-secondary-view");k.trigger("beforeSlideOut",a);0!==this.scrollTop&&p.scrollTop(this.scrollTop);c(b,window.innerWidth,window.scrollY);this.updateTimeout&&(clearTimeout(this.updateTimeout),
d.hide());e.delay(function(){g(b,!1);b.hide();k.trigger("afterSlideOut",a);p.unbind("touchmove.a-secondary-view")},m)},updatePosition:function(){var a=this.$popover,b=this.$iframe,c=b.is(":visible")?0:m;this.updateTimeout=e.delay(function(){b.height(a.height()).width(a.width());b.css("z-index",parseInt(a.css("z-index"),10)-1);b.show().css({top:"0px",left:"0px",opacity:"100","background-color":"white"})},c)}})}};e.declarative("a-secondary-view",["click"],function(a){s[a.type](a,a.data);a.$event.preventDefault()})});
"use strict";P.when("A","ready").register("a-changeover",function(e){var l=e.$;l(document).delegate(".a-changeover:not(.a-changeover-manual)","webkitAnimationEnd click touchstart",function(e){l(this).hide()})})})();
(function(){P.when("A").register("a-tabs",function(e){var l=e.$;e.declarative("a-tabs",["click"],function(k){var h=k.$target.closest("li"),m=k.data.name,g=h.data("a-tab-name");if(g){l("li.a-active",h.closest(".a-tabs")).removeClass("a-active");h.closest("li").addClass("a-active");var c={$tab:c,tabName:g,tabSetName:m};e.trigger("a:tabs:"+m+":select",{selectedTab:c});e.trigger("a:tabs:"+m+":"+g+":select",{selectedTab:c});k.$event.preventDefault()}})});"use strict";P.when("A").register("a-accordion",
function(e){var l=e.$;e.declarative("a-accordion",["click"],function(k){var h=k.$target.closest("div.a-box"),m=l("div.a-box",h.closest(".a-accordion")),g=k.data.name,c=h.data("a-accordion-row-name");if(c){var d=h.find(".a-accordion-inner").get(0);d.is(":hidden")&&(h.closest(".a-accordion").find(".a-accordion-inner").filter(":visible").attr("aria-expanded","false").slideUp(300),d.slideDown(300),e.delay(function(){m.removeClass("a-accordion-active");h.addClass("a-accordion-active");d.attr("aria-expanded",
"true");m.find("i.a-icon.a-accordion-radio").filter(".a-icon-touch-radio-active").removeClass("a-icon-touch-radio-active").addClass("a-icon-touch-radio-inactive");h.find("i.a-icon.a-accordion-radio").removeClass("a-icon-touch-radio-inactive").addClass("a-icon-touch-radio-active")},300));var a={$row:h,rowName:c,accordionName:g};e.trigger("a:accordion:"+g+":select",{selectedRow:a});e.trigger("a:accordion:"+g+":"+c+":select",{selectedRow:a});"a"===k.targetTag&&k.$target.has("i.a-icon.a-accordion-radio")&&
k.$event.preventDefault()}})});"use strict";P.when("A","jQuery").register("a-expander",function(e,l){function k(g){var c=g.$target.closest(".a-expander-container"),d=c.find(".a-expander-container"),a=c.data("a-expander-name");a&&e.trigger("a:expander:"+a+":toggle:expand",function(a){});var b;b=g.$currentTarget.hasClass("a-expander-header")?g.$currentTarget:c.find(".a-expander-header").not(d.find(".a-expander-header"));var k=c.find(".a-expander-content").not(d.find(".a-expander-content"));k.slideToggle(300,
function(){var a=b.find(".a-icon")[0],c=null;k.is(":hidden")?(a&&(a.className=a.className.replace(m.inline.collapse,h.inline.expand).replace(m.section.collapse,h.section.expand).replace(m.extender.collapse,h.extender.expand)),k.attr("aria-expanded","false"),g.data&&g.data.expand_prompt&&(c=g.data.expand_prompt)):(a&&(a.className=a.className.replace(m.inline.expand,h.inline.collapse).replace(m.section.expand,h.section.collapse).replace(m.extender.expand,h.extender.collapse)),k.attr("aria-expanded",
"true"),g.data&&g.data.collapse_prompt&&(c=g.data.collapse_prompt));c&&""!==c&&b.find(".a-expander-prompt").not(d.find(".a-expander-prompt")).html(c)})}var h={inline:{expand:"a-icon-expand",collapse:"a-icon-collapse"},section:{expand:"a-icon-section-expand",collapse:"a-icon-section-collapse"},extender:{expand:"a-icon-extender-expand",collapse:"a-icon-extender-collapse"}},m={};e.each(h,function(g,c){m[c]={};e.each(g,function(d,a){m[c][a]=new RegExp("\\b"+d+"\\b","g")})});e.declarative("a-expander-toggle",
"click",k);e.capabilities.touch&&e.declarative("a-expander-toggle","touchend",function(e){e.$currentTarget&&e.$currentTarget.nodeName&&"a"!==e.$currentTarget.nodeName.toLowerCase()&&k(e)})});"use strict";P.when("A","ready").register("a-form-controls",function(e){function l(e,g){var c=e.find("input"),d=e.find(".a-icon"),a={"multi-select":{active:"a-icon-touch-multi-select-active",inactive:"a-icon-touch-multi-select"},checkbox:{active:"a-icon-touch-checkbox-active",inactive:"a-icon-touch-checkbox-inactive"}};
c.attr("checked",!c.attr("checked"));d.toggleClass(a[g].active).toggleClass(a[g].inactive)}var k=e.$,h=k(document);h.delegate("label.a-touch-radio","click",function(e){var g=k(this),c=g.find("input"),g=g.find("i.a-icon"),d=c.closest("form");0===d.length&&(d=c.closest("fieldset"),0===d.length&&(d=k(document)));var a=d.find('i[data-a-input-name="'+c.attr("name")+'"]');d.find('input[name="'+c.attr("name")+'"]').attr("checked",!1);c.attr("checked",!0);a.addClass("a-icon-touch-radio-inactive").removeClass("a-icon-touch-radio-active");
g.addClass("a-icon-touch-radio-active").removeClass("a-icon-touch-radio-inactive");e.preventDefault()}).delegate("label.a-touch-checkbox","click",function(e){l(k(this),"checkbox");e.preventDefault()}).delegate("label.a-touch-multi-select","click",function(e){l(k(this),"multi-select");e.preventDefault()}).delegate("select.a-touch-select-input","change",function(e){var g=k(this),c=g.siblings("a.a-placeholder"),g=g.find(":selected").text();c.html(g);e.preventDefault()});e.capabilities.touch&&h.delegate("a:not(.a-button-text), .a-list-link li, .a-list-link li a.a-active, label, textarea, .a-touch-link, .a-input-text-wrapper, .a-button:not(.a-button-disabled), .a-accordion-row, .a-histogram-row",
"touchstart",function(e){k(".a-touch-press").removeClass("a-touch-press");this.className+=" a-touch-press"}).delegate("a:not(.a-button-text), .a-list-link li, .a-list-link li a.a-active, label, textarea, .a-touch-link, .a-input-text-wrapper, .a-button:not(.a-button-disabled), .a-accordion-row, .a-histogram-row","touchend",function(h){e.delay(function(){k(".a-touch-press").removeClass("a-touch-press")},300)})});"use strict";P.when("A","jQuery").register("a-buttons",function(e,l){e.declarative("a-button-group",
["click"],function(k){var h=k.$target.closest(".a-button");if(h.length){var m=k.$declarativeParent.find(".a-button"),g=k.data&&k.data.name?k.data.name:!1;k=k.$target.attr("name");m.removeClass("a-button-selected");h.addClass("a-button-selected");if(k||g)h={$button:h,buttonName:k,buttonGroupName:g},g&&(e.trigger("a:button-group:"+g+":toggle",{selectedButton:h}),k&&e.trigger("a:button-group:"+g+":"+k+":toggle",{selectedButton:h}))}})})})();
(function(){P.register("a-ios-timer-fix",function(){if(/OS 6_.*AppleWebKit/.test(window.navigator.userAgent)){var e=window.setTimeout,l=window.setInterval,k=window.clearTimeout,h={},m={};window.setTimeout=function(g,c){var d;d=e(function(){delete h[d];"function"===typeof g?g.apply(window,arguments):"string"===typeof g&&eval(g)},c);h[d]={startTime:Date.now(),fn:g,timeout:c,interval:!1};return d};window.setInterval=function(e,c){var d=l(e,c);h[d]={startTime:Date.now(),fn:e,timeout:c,interval:!0};return d};
window.clearTimeout=function(e){for(;;){k(e);h[e]&&delete h[e];if(!m[e])break;e=m[e]}};window.clearInterval=function(e){for(;;){k(e);h[e]&&delete h[e];if(!m[e])break;e=m[e]}};window.addEventListener("scroll",function(){var e,c,d;for(e in h)h.hasOwnProperty(e)&&(c=h[e],d=Date.now()-c.startTime>=c.timeout?c.timeout:Date.now()-c.startTime,c.interval?window.clearInterval(e):window.clearTimeout(e),d=c.interval?window.setInterval(c.fn,c.timeout):window.setTimeout(c.fn,c.timeout-d),c.interval&&(m[e]=d))},
!1)}});"use strict";P.when("A").register("a-ios-bug-fixes",function(e){e.on.load(function(){e.delay(function(){0===window.scrollY&&window.scrollTo(0,1)},10)})});"use strict";P.when("A").register("a-orientation-change",function(e){var l=e.$,k=function(){var c=document,d=c.activeElement;d&&d!==c.body&&d.scrollIntoView()};e.capabilities.touch&&e.on.ready(function(){e.on("orientationchange",function(){e.delay(k,1100);e.delay(k,2100);e.delay(k,3100)})});if(-1<navigator.userAgent.toLowerCase().indexOf("android")){var h,
m=window.orientation,g=function(){l(window).trigger("resize")};e.on("a:popover:beforeSlide",function(){h=e.interval(function(){window.orientation!==m&&(m=window.orientation,e.delay(g,1E3),e.delay(g,2E3),e.delay(g,3E3))},2E3)});e.on("a:popover:afterSlideOut",function(){clearInterval(h)})}})})();
(function(){P.when("A","ready").register("a-carousel-core",function(e){function l(a){return function(){throw"Abstract function called: "+a;}}function k(a,b){if(this===window)throw"invalid invocation";var c=this;this.dom=h(a);this.dom.addClass("a-carousel-initialized");this.$=function(b){return h(b,a)};this.content=this.dom.find(".a-content");this.container=this.dom;this.leftmostItemVisible=0;this.rightmostItemVisible=-1;this.parseOptions(b);this.gaugeFit();this.postProcessItems();this.bindHandlers();
c=this;h(window);c.trigger("initialized");h(window).bind("resize orientationchange",function(a){e.delay(function(){c.clearMeasurementCache();c.gaugeFit.call(c);c.moveToPosition(c._currentPosition)},500)})}var h=e.$,m={"3d":["MozTransform","webkitTransform"],"2d":["msTransform","OTransform"]},g=null,c=null,d=document.body.style,a;for(a in m["3d"])if(m["3d"][a]in d){g=m["3d"][a];c="3d";break}if(!g)for(a in m["2d"])if(m["2d"][a]in d){g=m["2d"][a];c="2d";break}var m=["MozTransition","webkitTransform",
"msTransition","OTransition"],b=null;for(a in m)if(m[a]in d){b=m[a];break}var p=function(){var a=this.$(this._groupingSelector+":visible"),b=e.reduce(a,function(a,b){var c=h(b).outerHeight();return c>a?c:a},0),c=this.dom.height();a.add(this.dom).height(Math.max(b,c))},f={};k.prototype={parseOptions:function(a){this.opts=h.extend(!0,{canMoveX:!0,canMoveY:!1,repaintAllCallback:[],type:"vanilla",maxWidth:150,margin:20,hasRestart:!0,hasDeadZone:!0,pageSnapping:!0,groupingSelector:"li.a-grouping"},a);
"productFaceout"===this.dom.data("aCarouselMode")&&this.opts.repaintAllCallback.push(p);this.totalElements=this.dom.data("totalElements");if(isNaN(this.totalElements)||0>=this.totalElements)throw"Total element count unknown, terminating";this.type=this.opts.type;(this.name=this.dom.data("a-carousel-name"))&&(f[this.name]=this);this._margin=this.opts.margin;this._padding=14;this._maxWidth=this.opts.maxWidth;this._hasRestart=!1;this._hasHistory=this.opts.hasHistory;this._groupingSelector=this.opts.groupingSelector;
this._currentPosition=0;this.pageSnapping=this.opts.pageSnapping;this._canMoveToPosition=this.opts.canMoveToPosition||this.pageSnapping;this.$(".a-content,ol").width((this._margin+this._padding+this._maxWidth)*(this.totalElements+(this._hasRestart?1:0)));this.placeholder=this.content.find(this._groupingSelector+".a-placeholder").detach();this.currentElements=this.content.find(this._groupingSelector).length;this.ajaxURL=this.dom.data("ajaxUrl");this._hiddenElements=this._offsetX=0;this._hasDeadZone=
this.opts.hasDeadZone;this._channel=this.dom.data("a-carousel-channel");this._itemsToShow=this.opts.itemsToShow;this._lastMeasurements=null;this.dom.addClass("a-carousel-no-restart");this._moveModerators=[]},cachedMeasurement:null,measure:function(){if(!this._cachedMeasurement){var a=this.container.innerWidth(),b=this.content.find(this._groupingSelector).not(".a-c-restart"),c=this._lastMeasurements||{},d=b.length,e=b.outerWidth(!0),f=b.outerHeight(!1),g=Math.max(Math.floor(a/e),1),k=[],m=[],l=0;b.each(function(a){a=
h(this).outerWidth(!0);k.push(a);m.push(l);l+=a});this._lastMeasurements=this._cachedMeasurement={containerWidth:a,elementWidth:e,elementOffsets:m,elementWidths:k,elementHeightNoMargin:f,elementCount:d,wholeElementsPerPage:g,changed:d!==c.elementCount||e!==c.elementWidth||g!==c.wholeElementsPerPage||f!==c.elementHeightNoMargin||a!==c.containerWidth}}return this._cachedMeasurement},clearMeasurementCache:function(){this._lastMeasurements=this._cachedMeasurement=null},calculateCardDimensions:l("calculateCardDimensions"),
trigger:function(a,b){var c={carousel:this};h.extend(c,b||{});e.trigger("carousel:"+a,c);e.trigger("carousel:"+this.name+":"+a,c)},gaugeFit:l("gaugeFit"),postGaugeFit:function(){this.snapToGrid();var a=this;e.each(this.opts.repaintAllCallback,function(b){b.call(a)});var b=0;this.content.find(this._groupingSelector).each(function(){var a=h(this).innerHeight();b=a>b?a:b});b=Math.min(b,window.innerHeight);this.dom.height(b)},registerMoveModerator:function(a){for(var b=0;b<this._moveModerators;b++)if(this._moveModerators[b]===
a)return;this._moveModerators.push(a)},queryMoveModerators:function(){var a=!0,b=this;e.each(b._moveModerators,function(c){if(!1===c.call(b))return a=!1,e.breaker});return a},loadMore:function(a){var b=[],c=!1,d=function(){b.shift();if(0<b.length){var d=b[0];a.apply(d[0],d[1])}else c=!1};return function(){if(c){if(2>b.length){var e=Array.prototype.slice(arguments,0);e.push(d);b.push([this,e])}}else e=Array.prototype.slice(arguments,0),e.push(d),c=!0,b.push([this,e]),a.apply(this,e)}}(function(a){var b=
this,c=b.measure(),d=b.$("li.a-placeholder:not(.a-loading):first"),f=!1;if(0<d.length&&b.ajaxURL){if(d.eq(0).position().left<-b._offsetX+2*c.containerWidth){for(c=d.next();c.is("li.a-placeholder:not(.a-loading)")&&10>d.length;)d=d.add(c),c=c.next();d.addClass("a-loading");var g=d.eq(0).prev(),f=!0;h.get(b.ajaxURL,{firstIdx:g.attr("aria-posinset")||0,count:d.length,total:b.totalElements}).success(function(a){e.defer(function(){d.remove();0<g.length?g.after(a):b.$("li.a-c-restart").closest("ol").prepend(a)});
e.defer(function(){b.clearMeasurementCache();b.gaugeFit();b.loadMore();b.trigger("ajaxSuccess")})}).error(function(c,d){setTimeout(a,1E3);b.trigger("ajaxError",{success:!1,textStatus:c,errorThrown:d})}).complete(function(){a()})}}else this.loadMore=function(){};f||setTimeout(a,500)}),postProcessItems:function(a){a||(a=this.$(this._groupingSelector+":not(.a-c-restart)"));var b=a.length,c=this.totalElements;if(b<c&&0<this.placeholder.length){for(var d=h("<div>").append(this.placeholder).html(),e="",
f=0;f<c-b;f++)e+=d;a=a.filter(":last");0<a.length?a.after(e):this.$(".a-c-restart").closest("ol").prepend(e)}},hashKey:function(){this._cachedHashKey||(this._cachedHashKey="Carousel:"+this.dom.attr("aria-label")+"|"+document.location.href);return this._cachedHashKey},_computeDecelerationRate:function(a,b){var c=.5;b&&(c=Math.abs(a-this._offsetX)/b,c=Math.min(c,.6),c=Math.max(c,.3));return c},moveToClosestPage:function(a){var b=this.measure();a=b.wholeElementsPerPage*Math.floor(a/b.wholeElementsPerPage);
a>=b.elementCount-b.wholeElementsPerPage&&(a=b.elementCount-b.wholeElementsPerPage);this.moveToPosition(a)},moveToPosition:function(a,b){e.pauseDeferred();var c=this._currentPosition;this._currentPosition=a;if(this._canMoveToPosition){var d=this.measure(),f=this;e.defer(function(){var b=f.content.find(f._groupingSelector).slice(Math.max(0,a-1),a+d.wholeElementsPerPage+2);e.loadDescendantImagesManually(b)});var g=-d.elementOffsets[a],k=this._computeDecelerationRate(g,b);this.content.css("-webkit-transition-duration",
1E3*k+"ms");this.moveToPixelPosition(this.content,g);f=this;setTimeout(function(){f.trigger("finishedMoving");c!==a&&f.trigger("positionChanged",{oldPosition:c});e.executeDeferred()},k)}},getCurrentPosition:function(){return this._currentPosition},setCurrentPosition:function(a){this._currentPosition=a},getChannel:function(){return this._channel},ensureIndexIsFullyVisible:function(a){var b=this.content.find("li").eq(a);if(0<b.length){a=this.measure();var c=a.elementWidth,b=b.offset().left,d=this.container.width();
b+c>d?this.moveToPosition(Math.min(this._currentPosition+a.wholeElementsPerPage,a.elementCount-2)):0>b&&this.moveToPosition(Math.max(this._currentPosition-a.wholeElementsPerPage,0))}},moveToPixelPosition:function(){k.prototype.moveToPixelPosition=b?"3d"===c?function(a,b){this._offsetX===b||isNaN(b)||(this._offsetX=b,a[0].style[g]="translate3d("+b+"px, 0, 0)")}:"2d"===c?function(a,b){this._offsetX!==b&&(this._offsetX=b,a[0].style[g]="translateX("+b+"px)")}:function(a,b){this._offsetX!==b&&(this._offsetX=
b,a.css("marginLeft",b+"px"))}:function(a,b){this._offsetX!==b&&(this._offsetX=b,a.animate({marginLeft:b+"px"},500))};this.moveToPixelPosition.apply(this,Array.prototype.slice.call(arguments,0))},bindHandlers:function(){this.bindDefaultClickHandlers()},bindDefaultClickHandlers:function(){var a=this;a.$(this._groupingSelector+".a-c-restart").click(function(b){a.moveToPosition(0);a.trigger("startOver")})},snapToGrid:function(a,b,c){"undefined"===typeof a&&(a=0);var d=this.measure(),e=Math.max(Math.floor(d.containerWidth/
d.elementWidth),1);Math.abs(this._offsetX/(e*d.elementWidth));if(this.pageSnapping){e=0;if(b||Math.abs(a/d.containerWidth)>=1/3)e=0<a?1:-1;a=(this._currentPosition||0)+e*d.wholeElementsPerPage;d.elementCount<=d.wholeElementsPerPage&&(a=0);a>=d.elementCount-d.wholeElementsPerPage&&1<d.wholeElementsPerPage&&(a=d.elementCount-d.wholeElementsPerPage);d=Math.floor((d.elementCount+(this._hasRestart?1:0))/d.wholeElementsPerPage)*d.wholeElementsPerPage}else d=(0<a?Math.ceil:Math.floor)(a/d.elementWidth),
a=(this._currentPosition||0)+d,d=this.totalElements-(this._hasRestart?0:1);--d;a=Math.min(a,d);a=Math.max(a,0);this.moveToPosition(a,c)}};h.fn.carousel=function(a){this.each(function(){var b=h(this);if(!b.data("carousel")){var c=new k(b,a);b.data("carousel",c)}})};k.get=function(a){return f[a]};return k});"use strict";P.when("A","a-carousel-core").register("a-carousel-support",function(e,l){var k=e.$;l.prototype.gaugeFit=function(){var e=this.measure();this.opts.gaugeFit&&this.opts.gaugeFit.call(this,
e);this.postGaugeFit()};l.prototype.calculateCardDimensions=function(){this.clearMeasurementCache();var e=this.measure();if(this.opts.calculateCardDimensions)return this._cachedCardDimensions=this.opts.calculateCardDimensions.call(this,e);e=e.containerWidth;k(document.documentElement).height();var m=this._maxWidth,g=this._margin,c=1/3,d=2,a;do a=d+c,a=(e-(d+1)*g)/a,d++;while(a>m);return this._cachedCardDimensions={cardWidth:a,fullCardsToShow:d-1}};l.prototype.bindHandlers=function(){this.bindDefaultClickHandlers();
this.bindTouchHandlers()};l.prototype.bindTouchHandlers=function(){function h(d){return function(k){var h=m.measure();if(1!==h.elementCount){var l=d?k.originalEvent:k,h=l.targetTouches[0].pageX,l=l.targetTouches[0].pageY;if(!f){var p=Math.abs(h-g),t=Math.abs(l-c);f=p>=t?"x":"y"}if(("x"!==f||m.opts.canMoveX)&&("y"!==f||m.opts.canMoveY)&&(k.preventDefault(),m.queryMoveModerators())){k=e.now();p=b[1];if(m.opts.canMoveY&&"y"===f)throw"not supported yet";if(m.opts.canMoveX&&"x"===f){if(p&&h===p[0]){p[2]=
k;return}b.push([h,l,k])}b.splice(0,b.length-2);h=m.measure();m.opts.canMoveX&&"x"===f&&(k=a+(b[1][0]-g),h=m.pageSnapping?-Math.floor(h.elementCount+(m._hasRestart?1:0)/h.wholeElementsPerPage)*h.wholeElementsPerPage*h.elementWidth:-h.elementWidth*(h.elementCount-Math.min(h.elementCount,h.wholeElementsPerPage)),0<k&&(k=Math.pow(k,.7)),k<h&&(k=h-Math.pow(h-k,.7)),m.content.data("a-dragging")||(m.content.data("a-dragging",!0),m.content.addClass("a-dragging")),m.moveToPixelPosition(m.content,k),m.loadMore())}}}}
var m=this,g,c,d,a,b=[],l=0,f;k("#minTouchMoveDelta");this.dom.delegate("a","click mousedown",function(a){500>e.now()-l&&a.preventDefault()});this.dom.delegate("*","click mousedown",function(a){m.content.hasClass("a-dragging")&&a.preventDefault()});m.container.bind("touchstart",function(k){m.container.data("a-carousel-first-interaction")||(m.clearMeasurementCache(),m.container.data("a-carousel-first-interaction",!0));a=m._offsetX||0;k=k.originalEvent.targetTouches[0];g=k.pageX;c=k.pageY;b=[];k=e.now();
b.push([g,c,k]);d=k;f=null;m.trigger("startedDragging")}).bind("touchend touchcancel",function(a){m.content.data("a-dragging",!1);m.content.removeClass("a-dragging");var h={oldPosition:m.getCurrentPosition()},s=!1,u="touchcancel"===a.type;h.canceled=u;if(2<=b.length&&!u){f&&(l=b[1][2]);var v=g-b[1][0],u=b[1][2]-d,t=Math.abs(1E3*v/u),y=300<=t,s=10>=Math.abs(v);h.distance={x:v,y:c-b[1][1]};h.duration=u;h.moving=!0;e.delay(function(){m.snapToGrid(v,y,t)})}else s=!u,h.distance={x:0,y:0},h.duration=0,
h.moving=!1;e.delay(function(){if(h.probablyClick=s)h.clickedIdx=k(a.target).closest(m._groupingSelector).prevAll().length,m._lastClickedIdx=h.clickedIdx,m.trigger("click",h);m.trigger("stoppedDragging",h)})});document.addEventListener?(m.container.get(0).addEventListener("touchmove",h(!1),!1),document.addEventListener("touchend",function(){e.now()},!1)):m.container.bind("touchmove",h(!0))}});"use strict";P.when("A","a-carousel-core","a-carousel-support").register("a-carousel",function(e,l){function k(c){e.$("div.a-carousel:not(.a-carousel-initialized):visible"+
(c?"":":not(.a-carousel-manual-initialization)")).each(function(c){var a=h(this);(c=a.data("carousel-subtype"))||(c="a:default");var b=m[c];b&&(e.onScreen(a)?a.carousel(b):e.defer(function(){a.carousel(b)}))})}var h=e.$;e.$(window);var m={"a:default":{calculateCardDimensions:function(c){c=c.containerWidth;h(document.documentElement).height();var d=this._maxWidth,a=this._margin,b=1/3,e=2,f;do f=e+b,f=(c-(e+1)*a)/f,e++;while(f>d);return{cardWidth:f,fullCardsToShow:e-1}},gaugeFit:function(c){c=this.calculateCardDimensions(!0);
this.$(this._groupingSelector).css({width:c.cardWidth+"px"})}}},g=!1;l.registerSubtype=function(c,d){if("a:default"===c)throw Error("Reserved carousel subtype name");d.type=c;m[c]=h.extend(!0,{},m["a:default"],d);g&&k()};e.on.ready(function(){g=!0});l.initializeAll=k;l.getCarousel=function(c){return h(c).closest(".a-carousel").data("carousel")};"function"===typeof Object.freeze&&Object.freeze(l);e.on("a:pageUpdate",k);e.on.ready(k);return l});"use strict";P.when("A","ue").register("a-carousel-metrics",
function(e,l){e.on("carousel:impression",function(e){e=e.carousel.dom.attr("id");l.log({id:e,event:"impression"},"auiCarousel")});e.on("carousel:startOver",function(e){e=e.carousel.dom.attr("id");l.log({id:e,event:"startOver"},"auiCarousel")});e.on("carousel:startedDragging",function(e){e=e.carousel.dom.attr("id");l.log({id:e,event:"startedDragging"},"auiCarousel")});e.on("carousel:stoppedDragging",function(e){var h=e.carousel.dom.attr("id");l.log({id:h,event:"stoppedDragging",distanceX:e.distance.x,
distanceY:e.distance.y,duration:e.duration},"auiCarousel")});e.on("carousel:ajaxSuccess",function(e){e=e.carousel.dom.attr("id");l.log({id:e,event:"ajaxSuccess"},"auiCarousel")});e.on("carousel:ajaxError",function(e){var h=e.carousel.dom.attr("id");l.log({id:h,event:"ajaxError",success:e.success,textStatus:e.textStatus,errorThrown:e.errorThrown},"auiCarousel")})});"use strict";P.when("A","a-carousel").execute(function(e,l){e.$(window);l.registerSubtype("companion",{hasRestart:!1,groupingSelector:"li.a-mini-grouping",
hasDeadZone:!1,calculateCardDimensions:function(e){return{cardWidth:46,fullCardsToShow:e.containerWidth/46}},gaugeFit:function(){}})});"use strict";P.when("A","a-carousel").execute(function(e,l){var k=e.$;e.$(window);l.registerSubtype("fixed-count",{hasRestart:!1,groupingSelector:"li.a-grouping",hasDeadZone:!0,itemsToShow:1.33,calculateCardDimensions:function(e){var k=e.containerWidth;return{cardWidth:1===e.elementCount?k:k/this._itemsToShow,fullCardsToShow:Math.floor(this._itemsToShow)}},gaugeFit:function(e){var l=
this.$(this._groupingSelector);l.children().height(l.height());this.content.css("width",e.containerWidth*l.length+"px");var g=this.calculateCardDimensions(!0);l.each(function(c){var d=k(this);d.data("a-image-width-calculated")||(d.width(e.elementWidths[c]>g.cardWidth?g.cardWidth:e.elementWidths[c]),d.data("a-image-width-calculated",!0))})}})});"use strict";P.when("A","a-carousel").execute(function(e,l){function k(c){e.defer(function(){e.loadHiResImage(c.dom.find("img"))});var d=c.dom.find("ol"),a=
d.height(),b=h(window).width();h(window).height();d.find(".a-immersive-image img").each(function(){var c=h(this),d=a,e=c.data("aspect-ratio"),g;e?(g=e*d,g>b&&(d*=b/g,g=b),c.css({height:d,"max-height":d,width:g,"max-width":g})):(g=new Image,g.src=c.attr("src"),g.onload=function(){e=this.naturalWidth/this.naturalHeight;c.data("aspect-ratio",e);var a=e*d;a>b&&(d*=b/a,a=b);c.css({height:d,"max-height":d,width:a,"max-width":a})})})}var h=e.$,m=e.$(window),g={maxWidth:Math.max(m.width(),m.height()),hasRestart:!1,
calculateCardDimensions:function(c){return{cardWidth:c.containerWidth,fullCardsToShow:1}},gaugeFit:function(c){c=this.$(this._groupingSelector);var d=m.width();c.css({width:d+"px"});this.dom.find("ol, ul").css("width",d*c.length+"px")}};l.registerSubtype("single",h.extend(!0,{},g,{hasDeadZone:!0}));l.registerSubtype("limelight",h.extend(!0,{},g,{hasDeadZone:!1,margin:0,gaugeFit:function(){g.gaugeFit.call(this);var c=this.$(this._groupingSelector),d=m.width(),a=window.innerHeight,d=d<=a,b=this.dom.find(".a-row.mini_carousel");
d?(b.show(),a=a-48-14):b.hide();this.container.add(this.content).add(c).css("height",a+"px");var h=this;e.defer(function(){k(h)})}}));e.on("carousel:initialized",function(c){var d=c.carousel;"limelight"===d.type&&e.defer(function(){k(d)})});e.on("carousel:positionChanged",function(c){var d=c.carousel;"limelight"===d.type&&e.defer(function(){k(d)})})})})();(function(){})();